# Contains the infrastructure and implementations for neutrino heating calculations

# Where is SPEC_HOME relative to this directory
CODE_HOME = ../../../code/SpEC/

# What subdirectories should also be compiled
SUBDIRECTORIES = \
	$(NULL)

# What .cpp files should be compiled (replace .cpp with .o)
OBJECT_FILES_INTO_LIB = \
	NeutrinoAnnihilationIntegral.o \
	$(NULL)

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules

