##############################################################################
# Makefile for NeutrinoAnnihilation
# Brett Deaton Spring 2012
##############################################################################
CODE_HOME = ../../../code/SpEC

SUBDIRECTORIES = 

LINKED_LIBS = \
	DataMesh MiscUtils \
	IO StringParsing Tensor Math \
	LowLevelUtils ErrorHandling

EXECUTABLES = \
	ComputeNuAnnihilationSinglePoint

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules
