##############################################################################
# Makefile for EOSManipAndVis
##############################################################################
CODE_HOME = ../../../Code/SpEC

SUBDIRECTORIES = \
	$(NULL)

LINKED_LIBS = \
	HydroStates \
	HydroComputeItems \
	EquationOfState \
	FiniteDifference \
	Functionals \
	SpherePack \
	SpatialCoordMaps \
	Domain \
	Slice \
	Subdomain \
	Topology \
	IndexMap \
	CoordMap \
	EinsteinSolutions \
	TensorFunctions \
	CoordinateTransformations \
	Functionals \
	Domain \
	Slice \
	Subdomain \
	Topology \
	DataMesh \
	IndexMap \
	CoordMap \
	MiscUtils \
	IO \
	DataBox \
	Vars \
	StringParsing \
	Tensor \
	Math \
	MpiWrappers \
	MyContainers \
	LowLevelUtils \
	ErrorHandling \
	$(NULL)

EXECUTABLES = \
	TOVSequence \
	PlotEOS \
	ConvertToTable \
	StellarProfile \
	TOVAddGridRadius \
	AppendPolytropeCrust \
	ConvertTabulatedEOSDatToVtk \
	$(NULL)

##############################################################################
# Nothing below here needs to be changed
##############################################################################
include $(CODE_HOME)/MakefileRules/this_machine.def
include $(CODE_HOME)/MakefileRules/Rules
